# Path to image directory. Images already needs to be preprocessed.
img_path: "data/owl_100pcs"

# Logging settings, optional.
logging:
  output_images_path: "./output/"
  store_new_matches: True
  store_trusted_clusters: True

# Model settings
model:
  id: "UNet_20250114_085543"
  directory: "models"
  activation_threshold: 0.8

# Defines the parameters of the piece representation
piece:
  # Polygon approximation precision
  # Smaller values mean more precise approximation, but large number of points
  polygon_approximation_tolerance: 3
  # Scale of the images. Smaller scale means faster but less precise computation.
  scale: 1

cluster:
  border_dist_tol: 4
  self_intersection_tol: 0.02
  rotation_tol: 0.17
  translation_tol: 30
  match_length_weight: 0.2
  min_border_length: 30

trusted_cluster:
  consistent_cycle_lengths: [3, 4]

clustering:
  n_iters: 20
  icp_max_iters: 100
  icp_min_change: 0.3
