# Path to image directory. Images already needs to be preprocessed.
img_path: "data/owl_101pcs"

# Logging settings, optional.
logging:
  output_images_path: "./output/puzzle"
  store_new_matches: True
  store_trusted_clusters: True

# Defines the parameters of the piece representation
piece:
  # Polygon approximation precision
  # Smaller values mean more precise approximation, but large number of points
  polygon_approximation_tolerance: 3
  # Scale of the images. Smaller scale means faster but less precise computation.
  scale: 0.5

cluster:
  border_dist_tol: 4
  self_intersection_tol: 0.02
  rotation_tol: 0.17
  translation_tol: 30

trusted_cluster:
  complexity_threshold: 4
  color_threshold: 0.01
  dist_threshold: 1.15

clustering:
  n_iters: 20
  icp_max_iters: 100
  icp_min_change: 0.3
